### PR TITLE
Mark edits2

### PR DESCRIPTION
**Pull request by schwabm**
The edits I think, even though I'm not the best writer, are generally
ok.

This comment:Note: In-house SSL certificates may prevent successful bootstrap. (i.e. `PEM_read_bio` errors)
This can be fixed by 'DOING THIS?'.
I don't know how you guys worked around that issue, but if you can change the DOING THIS to however you worked around it that would be cool.

Thanks

### CODE REVIEW

**Review by Jkovarik — CHANGES_REQUESTED** [review]
I've added a few comments/feedback to the PR.

**Review by flamingbear — CHANGES_REQUESTED** [review]
I'll make the changes I suggest here.

**Review by flamingbear — APPROVED** [review]

**Review by Jkovarik — APPROVED** [review]

**Review by schwabm — COMMENTED** [review]
Looks good to me Matt, thanks!

**Review by Jkovarik — APPROVED** [review]
Just two task-oriented comments, the updates look 'ok'.

**Pull request merged**
