### PR TITLE
Develop 1130

### PR DESCRIPTION
**Pull request by flamingbear**
@sflynn-itsc I turned this into a PR, so I can make comments inline and we can have a discussion about the changes.

I like some of the new wording you've added.
I'm not sure how I feel about all the duplication of documentation here though.  It will be really hard to keep them in sync.  It would be nice if we could have just one set of instructions.

### CODE REVIEW

**Review by flamingbear — COMMENTED** [review]
So there's lots in here.   

I'm going to take the obvious improvements and put them into another PR (the ones that apply to deployment.md) right away.

The rest we can work on.

**Review by flamingbear — COMMENTED** [review]
Need to submit review to see my comments

**Comment by scisco** [comment]
@flamingbear is this still relevant? If not, could you close it?

**Comment by scisco** [comment]
Closing this for lack of activity on this PR.

**Pull request closed without merging**
